a1 = int(input('Digite o Primeiro Valor:'))
a2 = int(input('Digite o Segundo Valor:'))
a3 = int(input('Digite o Terceiro Valor:'))
maximo = max(a1, a2, a3)
minimo = min(a1, a2, a3)
print(f'o maior valor é {maximo}')
print(f'o menor valor é {minimo}')